In [2]:
#import libraries
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [4]:
#load dataset
df=pd.read_csv(r"C:\Users\pc\Downloads\archive (1).zip")
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [5]:
#inspect datasets
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [10]:
#encode categorical variables
df["smoker"]=df["smoker"].map({"yes":1,"no":0})

In [11]:
df.head()

   age     sex     bmi  children  smoker     region      charges
0   19  female  27.900         0       1  southwest  16884.92400
1   18    male  33.770         1       0  southeast   1725.55230
2   28    male  33.000         3       0  southeast   4449.46200
3   33    male  22.705         0       0  northwest  21984.47061
4   32    male  28.880         0       0  northwest   3866.85520

In [12]:
#select variables
x=df[["age","bmi","children","smoker"]]
y=df["charges"]

In [ ]:
#justification
age,bmi,children,smoker were selected as independent variables because they influence individual medical insurance
insurance selected as dependent variable because it predicts the cost of medical insurance

In [13]:
x.head()

   age     bmi  children  smoker
0   19  27.900         0       1
1   18  33.770         1       0
2   28  33.000         3       0
3   33  22.705         0       0
4   32  28.880         0       0

In [14]:
y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [17]:
#split data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

model =LinearRegression()
model.fit(x_train,y_train)

In [18]:
#train Multiple linear Regression model
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [19]:
#get intercept
print("intercept:",model.intercept_)

intercept: -12117.075074107712

In [20]:
#get regression coefficients
coefficients = pd.DataFrame({
    "variable":x.columns,
    "coefficient":model.coef_
})
print(coefficients)

   variable   coefficient
0       age    257.071158
1       bmi    327.522631
2  children    427.199971
3    smoker  23653.211646

In [21]:
#prediction
y_predict=model.predict(x_test)
print(y_predict)

[ 8550.90921341  6969.71599759 36794.13661808  9421.86824203
 26875.01095777 11101.26514111   141.44896605 16750.22436643
   743.78364016 11157.63586446 28521.42342227  9296.15962897
  5456.5831315  38513.59317763 40362.63211366 37226.61219261
 15312.47750251 36042.83494384  9322.40796481 31395.64230108
  4273.49461256 10468.62243337  2723.96491222  6575.5287315
 11228.01912269 12468.20703945 14803.23875441  6062.13408867
  9531.77127863  2381.73787018  9470.9842188  12959.38866372
  4702.13338911  3410.73606761  4819.65393639 12488.16536441
  2355.2166747   9157.11135848 33234.15784494 32746.69484389
  4270.42403098  4233.52485656 14431.41993531 11388.84943272
  8929.60714179 12484.19557109  5150.40526844  3550.1037231
 35652.7853174   9280.12457197 15967.47938558  2556.74541518
 12158.95859481  1066.73450634 13555.51395976 12107.63444981
  3933.78585209 32050.44566484 13634.05117632 12397.82378122
 14493.62754566 10572.23545909 16669.43245629  7717.46643965
 11362.88637442  4002.4167569  27060.76239206 11178.82251312
  2111.07588471  6475.63432902 10213.54238103 11141.5791179
 11138.66980194  9355.18191748 12086.76718615  6936.96373448
  6777.77103761 10679.86525877  6743.56411652  9150.05856568
  3940.67737927 36217.76500227  6723.77632884 30313.42802916
 34840.04196096 34813.10220435  7216.54904091 12756.39284735
  9841.41659483 14776.62450822 17152.71129233 35518.43596997
 32602.2097042   5760.89390088 32155.61881714  9823.47106503
 29664.84331513  3832.59491101 28277.4190621   5420.13393472
  5325.53997161  2232.68096558 11608.90352975 15384.07666653
 11311.8133995   4466.20235446 10100.12536594 32006.13093351
  -457.8833414  33081.82571402  3608.27601617 10233.60302836
 13830.34769234 31158.27829801 10987.75822155  4259.79488196
 12672.70403915 32189.45055622  8336.65474969  3183.78071645
  7940.67175106 10478.51632722 14675.34366266  5797.59426775
  3745.09442887 10105.14052777 11037.09126095 10676.61172201
 14578.91985956  7522.03502791  5584.43169789  9402.59206618
  9479.77694712 11990.33096515  8651.44238589 15628.41282959
  7909.8082712  32158.80413898 35604.27400317 31128.91600147
  5942.93254912 12101.48401499  6167.62662597 14395.31181308
  2740.13639904 33371.60260973  6212.80691687  5383.03938723
 14192.06482663  7297.05567351 38514.99203859  3005.49794513
  5984.4868122  31204.19968127 11364.78442932  7980.19152943
 14338.08840334 10011.80899581 27264.76288877 32980.7370953
 14070.85976356  1626.54703542 13574.45833273  1823.14124689
  5787.15150838 11711.60492583 40079.2227154  36394.79776034
 33542.30197781  4233.63959682  7882.84367879  8980.38556751
 11879.17791531  4773.63023076  2414.35370347 32368.03102297
 25492.86545456 17593.5951415  26435.25310993 10127.95551792
 36817.09730971  -784.08774433  6802.0872111   8088.05693506
  3993.76045841  4973.87485055  5472.95926306  4667.43654574
 15235.79496174 11076.20174985  7228.25108519  2062.40330486
  1130.46498958 32248.81391928 16539.04048429 12162.07570174
  1222.05658602 12078.02098319  1128.96380625  9121.0621795
  1847.60312185 33864.85597242 10932.51035329  2551.58140563
 25895.46712072 26583.24295645  9386.35551068  1789.77190334
 13372.374146    1549.37457238 10830.32102434 10817.17359374
 16306.61101024 27082.74907633  7198.41128428  4742.76675089
  6052.53789027 13446.67798125 11341.32454375  8512.16463487
  4980.52762554 12137.7502566  13915.78570773 35910.10764543
  4055.24208524 29110.04594788  -485.75687249  2786.19421212
 11256.25856414 15770.57506077  5350.62819867  6905.3374727
  4249.44517329 31695.32550853  7255.75258051 12548.62062134
  5533.43620954  9848.43528017 36409.61376531  4598.92965286
  9312.32184413 31472.6534985   5604.32180795  4793.45212591
  1012.65916476  4741.26556756  4942.18964551  6853.36483075
 18698.30799775 -1507.6274815   2719.01796529 11008.92003441
  3531.00123076  9816.80901838  3617.88463247  5292.95824578
 12772.59844163  6101.90503712  7853.58370462  7121.53337044
  8843.99544289 10471.71785075 28024.34253326 39224.38864825
 11691.84197393  7257.65063541 40945.82704174 12622.0279358 ]

In [22]:
#evaluate model
mse=mean_squared_error(y_test,y_predict)
print(mse)

33981653.95019776

In [1]:
for variable,coefficient in zip(x.columns,model.coef_):
    print(variable,":",coefficient)

NameError: name 'x' is not defined

In [ ]:
#explanation
age_holding bmi,number of children,and smoking constant,an increase in age is associated with increase in predicted insurance charges 
BMI_holding other variables constant,increase in bmi is associated with change  in predicted insurance charges equal to bmi coefficient
children_holding other variables constant,an additional child is associated with a change in predicted insurance charges equal to the children coefficients
smoker_smoking status from non_smoker to smoker changes predicted insurance charges by the smoker coefficient holding other variables constant.

In [24]:
#interpret the intercept
print("intercept:",model.intercept_)

intercept: -12117.075074107712

In [29]:
#predict
new_person = pd.DataFrame({
    "age":[42],
    "bmi":[30],
    "children":[3],
    "smoker":[0]
 })
prediction=model.predict(new_person)
print("new_person:",prediction[0])

new_person: 9787.192405524898